/**
 * doctor/setup — `dsh-magic-context setup` (Phase 2 slice C).
 *
 * The DSH adapter's own setup tool (a package bin, NOT a dsh CLI command):
 *   1. locate the DSH install and the system standard preset
 *      (profile/install double anchor, dsh-reference §A.1);
 *   2. contract-scan the stock layout (scanStockPresetLayout) — a mismatch
 *      FAILS CLOSED and nothing is written;
 *   3. generate the `magic-standard` thin preset
 *      (`$DSH_HOME/.agent-presets/magic-standard/`: preset.yml metadata +
 *      agent.cordis.yml = buildThinPresetEntries output), atomic writes with
 *      0600 permissions;
 *   4. bootstrap/validate `~/.config/cortexkit/magic-context.jsonc` — never
 *      overwrites an existing file, only hints about missing keys;
 *   5. print next steps (profile install + preset usage).
 */
import { existsSync, readFileSync } from "node:fs";
import { load as yamlLoad, dump as yamlDump } from "js-yaml";
import { entryListSchema } from "@deepseek-ai/cordis-plugin-include";
import { resolveCortexKitUserConfigPath } from "@magic-context/core/config/migrate-config-location";
import {
  parseJsonc,
  readJsoncFile,
} from "@magic-context/core/shared/jsonc-parser";
import {
  buildThinPresetEntries,
  scanStockPresetLayout,
} from "../compat/dsh-0.1/preset";
import {
  DSH_COMPAT_EXPECTED_VERSION,
  MAGIC_CONTEXT_PACKAGE,
  errorMessage,
  locateDshInstall,
  magicEntryPath,
  magicStandardAgentCordisPath,
  magicStandardDir,
  magicStandardPresetYamlPath,
  parseFlags,
  resolveDshHome,
  stringFlag,
  writeFileAtomic,
} from "./env";

/** Thin preset identity (dsh-reference §A.6 custom preset metadata). */
export const MAGIC_STANDARD_PRESET = {
  id: "magic-standard",
  name: "Magic Context standard",
  description:
    "Stock `standard` preset with the Magic Context compaction engine enabled " +
    "(compaction-basic disabled) and the Magic agent rows mounted.",
  order: 10,
} as const;

/** Recommended top-level keys checked when a user config already exists. */
export const RECOMMENDED_CONFIG_KEYS = [
  "enabled",
  "transform_mode",
  "sqlite",
  "embedding",
  "compaction",
] as const;

export type SetupStepStatus = "ok" | "warn" | "fail";

export interface SetupStep {
  readonly status: SetupStepStatus;
  readonly title: string;
  readonly detail: string;
}

export interface SetupReport {
  readonly exitCode: number;
  readonly steps: readonly SetupStep[];
  /** Files actually written by this run (empty on dry-run / failure). */
  readonly generatedFiles: readonly string[];
  readonly nextSteps: readonly string[];
}

export interface DshSetupOptions {
  readonly env?: NodeJS.ProcessEnv;
  /** DSH home override (tests / `--dsh-home`). */
  readonly dshHome?: string;
  /** DSH install override (tests / `--dsh-install`). */
  readonly dshInstallDir?: string;
  /** Stock preset override (tests / `--stock-preset`). */
  readonly stockPresetPath?: string;
  /** Validate + report but write nothing. */
  readonly dryRun?: boolean;
  /** Profile name for the next-steps hint. */
  readonly profile?: string;
}

/** Minimal, schema-valid user config (JSONC with a comment header). */
export function defaultMagicConfigJsonc(): string {
  return [
    "// Magic Context — generated by `dsh-magic-context setup`.",
    "// Edit this file with your editor: the DSH settings card is read-only on",
    "// purpose, so this file stays the single source of truth.",
    "// Full schema: packages/plugin/src/config/schema/magic-context.ts",
    "{",
    '  "enabled": true,',
    '  "transform_mode": "ts",',
    '  "sqlite": { "cache_size_mb": 64, "mmap_size_mb": 0 },',
    '  "embedding": { "provider": "local", "model": "Xenova/all-MiniLM-L6-v2" },',
    '  "compaction": { "enabled": true }',
    "}",
    "",
  ].join("\n");
}

/** Keys the user explicitly carries; only used for the "missing key" hint. */
function presentTopLevelKeys(configPath: string): Set<string> {
  const parsed = readJsoncFile<Record<string, unknown>>(configPath);
  if (parsed === null || typeof parsed !== "object") return new Set();
  return new Set(Object.keys(parsed));
}

/** Parse a stock/standard `agent.cordis.yml` entry list (loader YAML dialect). */
export function parseEntryListYaml(text: string): Record<string, unknown>[] {
  return yamlLoad(text, { schema: entryListSchema }) as Record<string, unknown>[];
}

/** Render an entry list back to the loader YAML dialect. */
export function dumpEntryListYaml(entries: Record<string, unknown>[]): string {
  return yamlDump(entries, { schema: entryListSchema });
}

export async function runDshSetup(
  argv: readonly string[],
  options: DshSetupOptions = {},
): Promise<SetupReport> {
  const { flags } = parseFlags(argv);
  const env = options.env ?? process.env;
  const dshHome = options.dshHome ?? stringFlag(flags, "dsh-home") ?? resolveDshHome(env);
  const dshInstallDir = options.dshInstallDir ?? stringFlag(flags, "dsh-install");
  const stockPresetPath = options.stockPresetPath ?? stringFlag(flags, "stock-preset");
  const dryRun = options.dryRun ?? flags["dry-run"] === true;
  const profile = options.profile ?? stringFlag(flags, "profile");

  const steps: SetupStep[] = [];
  const generatedFiles: string[] = [];
  let failed = false;

  // 1. DSH home.
  steps.push({ status: "ok", title: "DSH home", detail: dshHome });

  // 2. DSH install + system standard preset.
  const located = locateDshInstall({ dshHome, dshInstallDir, stockPresetPath, env });
  if (located.stockPresetPath === undefined) {
    steps.push({
      status: "fail",
      title: "DSH install / system standard preset",
      detail:
        `Could not locate the system standard preset ` +
        `(${DSH_COMPAT_EXPECTED_VERSION} expected). Probed:\n` +
        located.tried.map((candidate) => `  - ${candidate}`).join("\n") +
        `\nFix: install DSH ${DSH_COMPAT_EXPECTED_VERSION}, or pass ` +
        `--dsh-install <dir> / --stock-preset <file>.`,
    });
    failed = true;
  } else {
    steps.push({
      status: "ok",
      title: "DSH install / system standard preset",
      detail: located.stockPresetPath,
    });
  }

  // 3. Contract scan (fail closed — nothing is written on a mismatch).
  let stockEntries: Record<string, unknown>[] | undefined;
  if (!failed && located.stockPresetPath !== undefined) {
    try {
      stockEntries = parseEntryListYaml(
        readFileSync(located.stockPresetPath, "utf8"),
      );
      const layoutIssue = scanStockPresetLayout(stockEntries);
      if (layoutIssue !== undefined) {
        steps.push({
          status: "fail",
          title: "Stock preset contract scan",
          detail:
            `${located.stockPresetPath}: ${layoutIssue}. The guarded patch cannot ` +
            `be applied — refusing to generate magic-standard (fail closed). ` +
            `Fix: check that the DSH install matches ${DSH_COMPAT_EXPECTED_VERSION}.`,
        });
        failed = true;
      } else {
        steps.push({
          status: "ok",
          title: "Stock preset contract scan",
          detail: `${located.stockPresetPath}: compaction group + compaction-basic match the expected layout.`,
        });
      }
    } catch (error) {
      steps.push({
        status: "fail",
        title: "Stock preset contract scan",
        detail: `${located.stockPresetPath}: ${errorMessage(error)}`,
      });
      failed = true;
    }
  }

  // 4. Generate the thin preset (atomic, 0600).
  if (!failed && stockEntries !== undefined && located.stockPresetPath !== undefined) {
    try {
      const presetDir = magicStandardDir(dshHome);
      const presetYamlPath = magicStandardPresetYamlPath(dshHome);
      const agentCordisPath = magicStandardAgentCordisPath(dshHome);
      const thinEntries = buildThinPresetEntries({
        stockPresetPath: located.stockPresetPath,
        magicEngineEntry: magicEntryPath("compaction"),
        includeEntry: magicEntryPath("preset-include"),
        magicRows: [
          { id: "magic-agent", name: magicEntryPath("agent") },
        ],
      });
      const presetYaml = yamlDump({
        name: MAGIC_STANDARD_PRESET.name,
        description: MAGIC_STANDARD_PRESET.description,
        order: MAGIC_STANDARD_PRESET.order,
      });
      const agentCordis = dumpEntryListYaml(thinEntries);

      if (dryRun) {
        steps.push({
          status: "ok",
          title: "Generate magic-standard preset (dry run)",
          detail:
            `${presetDir} would be written with agent.cordis.yml (include row ` +
            `over the stock file + guarded patches).`,
        });
      } else {
        const unchangedPreset = existsSync(presetYamlPath) &&
          readFileSync(presetYamlPath, "utf8") === presetYaml;
        const unchangedAgent = existsSync(agentCordisPath) &&
          readFileSync(agentCordisPath, "utf8") === agentCordis;
        if (unchangedPreset && unchangedAgent) {
          steps.push({
            status: "ok",
            title: "Generate magic-standard preset",
            detail: `${presetDir} already up to date (unchanged).`,
          });
        } else {
          writeFileAtomic(presetYamlPath, presetYaml);
          writeFileAtomic(agentCordisPath, agentCordis);
          generatedFiles.push(presetYamlPath, agentCordisPath);
          steps.push({
            status: "ok",
            title: "Generate magic-standard preset",
            detail: `wrote ${presetDir} (preset.yml + agent.cordis.yml, 0600).`,
          });
        }
      }
    } catch (error) {
      steps.push({
        status: "fail",
        title: "Generate magic-standard preset",
        detail: errorMessage(error),
      });
      failed = true;
    }
  }

  // 5. Bootstrap / validate the user config (never overwrite an existing file).
  const configPath = resolveCortexKitUserConfigPath();
  if (existsSync(configPath)) {
    let missing: string[] = [];
    try {
      parseJsonc(readFileSync(configPath, "utf8"));
      const present = presentTopLevelKeys(configPath);
      missing = RECOMMENDED_CONFIG_KEYS.filter((key) => !present.has(key));
    } catch (error) {
      steps.push({
        status: "warn",
        title: "Magic Context user config",
        detail: `${configPath} exists but is not valid JSONC (${errorMessage(error)}); leaving untouched.`,
      });
      missing = [];
    }
    if (missing.length === 0) {
      steps.push({
        status: "ok",
        title: "Magic Context user config",
        detail: `${configPath} exists and carries the recommended keys; not overwritten.`,
      });
    } else {
      steps.push({
        status: "warn",
        title: "Magic Context user config",
        detail:
          `${configPath} exists; not overwritten. Missing recommended keys: ` +
          `${missing.join(", ")} (defaults apply).`,
      });
    }
  } else {
    if (failed) {
      steps.push({
        status: "warn",
        title: "Magic Context user config",
        detail:
          `${configPath} does not exist; not created because earlier steps ` +
          `failed (fail closed — nothing partial is written).`,
      });
    } else if (dryRun) {
      steps.push({
        status: "ok",
        title: "Magic Context user config (dry run)",
        detail: `${configPath} would be created from defaults.`,
      });
    } else {
      try {
        writeFileAtomic(configPath, defaultMagicConfigJsonc());
        generatedFiles.push(configPath);
        steps.push({
          status: "ok",
          title: "Magic Context user config",
          detail: `created ${configPath} from defaults.`,
        });
      } catch (error) {
        steps.push({
          status: "fail",
          title: "Magic Context user config",
          detail: `could not create ${configPath}: ${errorMessage(error)}`,
        });
        failed = true;
      }
    }
  }

  // 6. Next steps.
  const nextSteps: string[] = [];
  if (failed) {
    nextSteps.push("Fix the failing steps above, then re-run `dsh-magic-context setup`.");
  } else {
    if (profile !== undefined) {
      nextSteps.push(
        `Install the bundle into the profile: dsh plugin --profile ${profile} add ${MAGIC_CONTEXT_PACKAGE}`,
      );
    } else {
      nextSteps.push(
        `Install the bundle into a profile: dsh plugin --profile <name> add ${MAGIC_CONTEXT_PACKAGE} ` +
        `(or add it to the profile's dsh.profile.bundles manually).`,
      );
    }
    nextSteps.push(
      "Select the `magic-standard` preset for new sessions (Settings → Agent preset), " +
      `or set it as the default in settings.yaml (agent-presets.default). Preset location: ${magicStandardDir(dshHome)}`,
    );
    nextSteps.push("Verify with: dsh-magic-context doctor");
  }

  return {
    exitCode: failed ? 1 : 0,
    steps,
    generatedFiles,
    nextSteps,
  };
}
